### ISSUE TITLE
Cop crashing after updating `use_packwerk` to latest version

### ISSUE THREAD

**Issue by iMacTia** [rubyatscale/rubocop-packs#23]
In our project we don't explicitly use `rubocop-packs`, but we do use `use_packwerk`.
After updating `use_packwerk` from v0.55.0 to v0.58.1, we started getting the following issue while running Rubocop:

```
An error occurred while Packs/NamespaceConvention cop was inspecting path/to/file.rb.
undefined method `include?' for nil:NilClass

            package_enforces_namespaces = cop_config['IncludePacks'].include?(package_for_path.name)
                                                                    ^^^^^^^^^
.../rubocop-packs-0.0.12/lib/rubocop/cop/packs/namespace_convention.rb:60:in `on_new_investigation'
```

The interesting bit is that we are not requiring `rubocop-packs` in our `.rubocop.yml` file, so I'm unsure as to why this cop is even running to begin with.
I've nonetheless attempted to explicitly require it, but to no avail.

**Comment by alexevanczuk** [comment]
Thanks for reporting this @iMacTia . Let me get this fixed for you.

**Comment by alexevanczuk** [comment]
@iMacTia So I am in the mist of trying to migrate `package_protections` to `rubocop-packs` and I think this is a fallout from that.

**Comment by alexevanczuk** [comment]
@iMacTia So I am in the mist of trying to migrate `package_protections` to `rubocop-packs` and I think this is a fallout from that.

Can you try `bundle update rubocop-packs --conservative` to update to `0.0.13` which should fix this for ya? Apologies for this -- since we're still in the early stages of some of this toolchain there is some turbulence but I'm hoping to land on something more stable at some point in the future.

**Comment by iMacTia** [comment]
Hey @alexevanczuk, thank you for the quick reply! I completely understand, I'm merely reporting to help identifying possible bugs 🙌

I'll try your suggestion and report back ASAP 👍

**Comment by iMacTia** [comment]
All good, getting the new cop offenses correctly now. I'll look into them 👍!
Closing this issue now, though I have a follow-up question if you don't mind 🙏 

> I am in the mist of trying to migrate `package_protections` to `rubocop-packs`

We had already configured `package_protections` cops in our project, is `rubocop-packs` a superset or should we keep both for the time being?
